[@ww.textfield labelKey="com.drextended.gppublisher.bamboo.applicationName" name="applicationName" required='true'/]
[@ww.textfield labelKey="com.drextended.gppublisher.bamboo.packageName" name="packageName" required='true'/]

[@ww.checkbox labelKey='com.drextended.gppublisher.bamboo.findJsonKeyInFile' name='findJsonKeyInFile' toggle='true'/]
    [@ui.bambooSection dependsOn='findJsonKeyInFile' showOn='true']
        [@ww.textfield labelKey="com.drextended.gppublisher.bamboo.jsonKeyPath" name="jsonKeyPath" required='true'/]
    [/@ui.bambooSection]

    [@ui.bambooSection dependsOn='findJsonKeyInFile' showOn='false']
        [@ww.textarea labelKey="com.drextended.gppublisher.bamboo.jsonKeyContent" name="jsonKeyContent" required='true'/]
    [/@ui.bambooSection]

[@ww.textfield labelKey="com.drextended.gppublisher.bamboo.apkPath" name="apkPath" required='true'/]
[@ww.textfield labelKey="com.drextended.gppublisher.bamboo.deobfuscationFilePath" name="deobfuscationFilePath" required='false'/]
[@ww.textfield labelKey="com.drextended.gppublisher.bamboo.recentChangesListings" name="recentChangesListings" required='false'/]
[@ww.select labelKey="com.drextended.gppublisher.bamboo.track" name="track" list="trackTypes" required='true'/]
    [@ui.bambooSection dependsOn='track' showOn='rollout']
        [@ww.select labelKey="com.drextended.gppublisher.bamboo.rolloutFraction" name="rolloutFraction" list="rolloutFractions" required='true'/]
    [/@ui.bambooSection]
    [@ui.bambooSection dependsOn='track' showOn='custom']
            [@ww.textfield labelKey="com.drextended.gppublisher.bamboo.customTrackNames" name="trackCustomNames" required='true'/]
    [/@ui.bambooSection]
[@ww.label labelKey="com.drextended.gppublisher.bamboo.branding" name="googlePlayBranding"/]