[@ww.textfield labelKey="com.drextended.gppublisher.bamboo.applicationName" name="applicationName" required='true'/]
[@ww.textfield labelKey="com.drextended.gppublisher.bamboo.packageName" name="packageName" required='true'/]
[@ww.textfield labelKey="com.drextended.gppublisher.bamboo.jsonKeyPath" name="jsonKeyPath" required='true'/]
[@ww.textfield labelKey="com.drextended.gppublisher.bamboo.apkPath" name="apkPath" required='true'/]
[@ww.radio labelKey="com.drextended.gppublisher.bamboo.track" name="track" list="trackTypes" toggle="true"/]
[@ww.label labelKey="com.drextended.gppublisher.bamboo.branding" name="googlePlayBranding"/]